package com.dao;

import com.bean.Classify;
import com.bean.ClassifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    long countByExample(ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    int deleteByExample(ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    int insert(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    int insertSelective(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    List<Classify> selectByExample(ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    Classify selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Classify record, @Param("example") ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Classify record, @Param("example") ClassifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Classify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Classify record);
}