package com.dao;

import com.bean.Essay;
import com.bean.EssayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EssayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    long countByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    int deleteByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    int insert(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    int insertSelective(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    List<Essay> selectByExample(EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    Essay selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") Essay record, @Param("example") EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    int updateByExample(@Param("record") Essay record, @Param("example") EssayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    int updateByPrimaryKeySelective(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Thu Oct 24 14:58:09 CST 2019
     */
    int updateByPrimaryKey(Essay record);
}