package com.dao;

import com.bean.power;
import com.bean.powerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface powerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    long countByExample(powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    int deleteByExample(powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    int insert(power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    int insertSelective(power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    List<power> selectByExample(powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    power selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") power record, @Param("example") powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    int updateByExample(@Param("record") power record, @Param("example") powerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    int updateByPrimaryKeySelective(power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated Sat Oct 12 16:22:20 CST 2019
     */
    int updateByPrimaryKey(power record);
}