package com.dao;

import com.bean.pro;
import com.bean.proExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface proMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    long countByExample(proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    int deleteByExample(proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    int insert(pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    int insertSelective(pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    List<pro> selectByExample(proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") pro record, @Param("example") proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    int updateByExample(@Param("record") pro record, @Param("example") proExample example);
}