package com.dao;

import com.bean.user_info;
import com.bean.user_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface user_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    long countByExample(user_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    int deleteByExample(user_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    int insert(user_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    int insertSelective(user_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    List<user_info> selectByExample(user_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    user_info selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") user_info record, @Param("example") user_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    int updateByExample(@Param("record") user_info record, @Param("example") user_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    int updateByPrimaryKeySelective(user_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Oct 10 09:55:20 CST 2019
     */
    int updateByPrimaryKey(user_info record);
}