package com.bean;

public class classify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classify.cid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classify.cname
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classify.cid
     *
     * @return the value of classify.cid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classify.cid
     *
     * @param cid the value for classify.cid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classify.cname
     *
     * @return the value of classify.cname
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classify.cname
     *
     * @param cname the value for classify.cname
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }
}