package com.bean;

import java.util.Date;

public class essay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.eid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.ename
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.eclass
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private String eclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.ctime
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.modified
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.e_score
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Integer eScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.publish
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Date publish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.writer
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private String writer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.eid
     *
     * @return the value of essay.eid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.eid
     *
     * @param eid the value for essay.eid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.ename
     *
     * @return the value of essay.ename
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.ename
     *
     * @param ename the value for essay.ename
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.eclass
     *
     * @return the value of essay.eclass
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public String getEclass() {
        return eclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.eclass
     *
     * @param eclass the value for essay.eclass
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setEclass(String eclass) {
        this.eclass = eclass == null ? null : eclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.ctime
     *
     * @return the value of essay.ctime
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.ctime
     *
     * @param ctime the value for essay.ctime
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.modified
     *
     * @return the value of essay.modified
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.modified
     *
     * @param modified the value for essay.modified
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.e_score
     *
     * @return the value of essay.e_score
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Integer geteScore() {
        return eScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.e_score
     *
     * @param eScore the value for essay.e_score
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void seteScore(Integer eScore) {
        this.eScore = eScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.publish
     *
     * @return the value of essay.publish
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Date getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.publish
     *
     * @param publish the value for essay.publish
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setPublish(Date publish) {
        this.publish = publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.writer
     *
     * @return the value of essay.writer
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public String getWriter() {
        return writer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.writer
     *
     * @param writer the value for essay.writer
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setWriter(String writer) {
        this.writer = writer == null ? null : writer.trim();
    }
}