package com.bean;

import java.util.Date;

public class Essay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.eid
     *
     * @mbg.generated
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.ename
     *
     * @mbg.generated
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.eclass_id
     *
     * @mbg.generated
     */
    private Integer eclassId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.c_time
     *
     * @mbg.generated
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.modified
     *
     * @mbg.generated
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.e_score
     *
     * @mbg.generated
     */
    private Integer eScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.publish
     *
     * @mbg.generated
     */
    private Date publish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column essay.writer_id
     *
     * @mbg.generated
     */
    private Integer writerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.eid
     *
     * @return the value of essay.eid
     *
     * @mbg.generated
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.eid
     *
     * @param eid the value for essay.eid
     *
     * @mbg.generated
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.ename
     *
     * @return the value of essay.ename
     *
     * @mbg.generated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.ename
     *
     * @param ename the value for essay.ename
     *
     * @mbg.generated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.eclass_id
     *
     * @return the value of essay.eclass_id
     *
     * @mbg.generated
     */
    public Integer getEclassId() {
        return eclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.eclass_id
     *
     * @param eclassId the value for essay.eclass_id
     *
     * @mbg.generated
     */
    public void setEclassId(Integer eclassId) {
        this.eclassId = eclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.c_time
     *
     * @return the value of essay.c_time
     *
     * @mbg.generated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.c_time
     *
     * @param cTime the value for essay.c_time
     *
     * @mbg.generated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.modified
     *
     * @return the value of essay.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.modified
     *
     * @param modified the value for essay.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.e_score
     *
     * @return the value of essay.e_score
     *
     * @mbg.generated
     */
    public Integer geteScore() {
        return eScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.e_score
     *
     * @param eScore the value for essay.e_score
     *
     * @mbg.generated
     */
    public void seteScore(Integer eScore) {
        this.eScore = eScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.publish
     *
     * @return the value of essay.publish
     *
     * @mbg.generated
     */
    public Date getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.publish
     *
     * @param publish the value for essay.publish
     *
     * @mbg.generated
     */
    public void setPublish(Date publish) {
        this.publish = publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.writer_id
     *
     * @return the value of essay.writer_id
     *
     * @mbg.generated
     */
    public Integer getWriterId() {
        return writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.writer_id
     *
     * @param writerId the value for essay.writer_id
     *
     * @mbg.generated
     */
    public void setWriterId(Integer writerId) {
        this.writerId = writerId;
    }
}