package com.bean;

public class Power {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.p_num
     *
     * @mbg.generated
     */
    private Integer pNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.p_id
     *
     * @return the value of power.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.p_id
     *
     * @param pId the value for power.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.p_name
     *
     * @return the value of power.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.p_name
     *
     * @param pName the value for power.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.p_num
     *
     * @return the value of power.p_num
     *
     * @mbg.generated
     */
    public Integer getpNum() {
        return pNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.p_num
     *
     * @param pNum the value for power.p_num
     *
     * @mbg.generated
     */
    public void setpNum(Integer pNum) {
        this.pNum = pNum;
    }
}