package com.bean;

import java.util.Date;

public class pro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.last_check_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Date lastCheckTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.id
     *
     * @return the value of pro.id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.id
     *
     * @param id the value for pro.id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.last_check_time
     *
     * @return the value of pro.last_check_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Date getLastCheckTime() {
        return lastCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.last_check_time
     *
     * @param lastCheckTime the value for pro.last_check_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setLastCheckTime(Date lastCheckTime) {
        this.lastCheckTime = lastCheckTime;
    }
}