package com.bean;

import java.util.Date;

public class reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.repuser_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Integer repuserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.topic_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Integer topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.user_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.create_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.update_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rid
     *
     * @return the value of reply.rid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rid
     *
     * @param rid the value for reply.rid
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.repuser_id
     *
     * @return the value of reply.repuser_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Integer getRepuserId() {
        return repuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.repuser_id
     *
     * @param repuserId the value for reply.repuser_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setRepuserId(Integer repuserId) {
        this.repuserId = repuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.topic_id
     *
     * @return the value of reply.topic_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.topic_id
     *
     * @param topicId the value for reply.topic_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.user_id
     *
     * @return the value of reply.user_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.user_id
     *
     * @param userId the value for reply.user_id
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.create_time
     *
     * @return the value of reply.create_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.create_time
     *
     * @param createTime the value for reply.create_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.update_time
     *
     * @return the value of reply.update_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.update_time
     *
     * @param updateTime the value for reply.update_time
     *
     * @mbg.generated Mon Sep 30 19:38:06 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}